@extends('layouts.app')

@section('title', 'Riwayat Kolaborasi')
@section('breadcrumb', 'Riwayat Kolaborasi')

@section('content')
<style>
.history-page{color:#e2e8f0}.history-page .history-hero{padding:4px 0 20px}.history-page .kicker{font-size:.7rem;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#3b82f6}.history-page h1{font-size:1.5rem;font-weight:750;letter-spacing:-.03em;margin:3px 0;color:#f8fafc}.history-page .subtitle{font-size:.84rem;color:#94a3b8;margin:0}.history-page .history-card{background:#0f172a;border:1px solid rgba(148,163,184,.14);border-radius:14px;box-shadow:0 8px 24px rgba(0,0,0,.16);overflow:hidden}.history-page .filter{padding:15px 18px;border-bottom:1px solid rgba(148,163,184,.12);background:#111c35}.history-page .form-label{color:#94a3b8}.history-page .form-control,.history-page .form-select{background:#1e293b;color:#e2e8f0;border:1px solid #334155;border-radius:9px;min-height:40px}.history-page .form-control:focus,.history-page .form-select:focus{background:#1e293b;color:#fff;border-color:#3b82f6;box-shadow:0 0 0 .2rem rgba(59,130,246,.15)}.history-page .table{margin:0;color:#cbd5e1;vertical-align:middle}.history-page .table thead th{background:#111c35;color:#64748b;border-bottom:1px solid #24324a;font-size:.68rem;text-transform:uppercase;letter-spacing:.05em;padding:12px 14px}.history-page .table tbody td{padding:12px 14px;border-color:rgba(148,163,184,.1);background:#0f172a;font-size:.81rem}.history-page .table tbody tr:hover td{background:#111c35}.history-page .text-muted{color:#64748b!important}.history-page .card-foot{padding:12px 18px;border-top:1px solid rgba(148,163,184,.12)}.history-page .btn-outline-primary{color:#60a5fa;border-color:#2563eb}.history-page .page-link{background:#1e293b;border-color:#334155;color:#94a3b8}.history-page .page-item.active .page-link{background:#2563eb;border-color:#2563eb;color:#fff}
</style>
<div class="container-fluid history-page">
<div class="history-hero"><div class="d-flex justify-content-between align-items-center gap-3"><div><div class="kicker"><i class="fas fa-clock-rotate-left me-1"></i> Aktivitas</div><h1>Riwayat Kolaborasi</h1><p class="subtitle">Pantau seluruh aktivitas berbagi soal dan paket soal.</p></div><a href="{{ route('share.index') }}" class="btn btn-outline-primary"><i class="fas fa-arrow-left me-1"></i> Kembali</a></div></div>
<div class="history-card"><div class="filter"><form method="GET" class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label small">Jenis</label><select name="type" class="form-select form-select-sm"><option value="">Semua Jenis</option><option value="soal" {{ request('type') == 'soal' ? 'selected' : '' }}>Soal</option><option value="paket" {{ request('type') == 'paket' ? 'selected' : '' }}>Paket Soal</option></select></div><div class="col-md-3"><label class="form-label small">Status</label><select name="status" class="form-select form-select-sm"><option value="">Semua Status</option><option value="accepted" {{ request('status') == 'accepted' ? 'selected' : '' }}>Diterima</option><option value="pending" {{ request('status') == 'pending' ? 'selected' : '' }}>Pending</option><option value="rejected" {{ request('status') == 'rejected' ? 'selected' : '' }}>Ditolak</option></select></div><div class="col-md-4"><label class="form-label small">Cari</label><input type="text" name="search" class="form-control form-control-sm" placeholder="Cari judul..." value="{{ request('search') }}"></div><div class="col-md-2"><button type="submit" class="btn btn-primary btn-sm w-100"><i class="fas fa-search me-1"></i> Filter</button></div></form></div><div class="table-responsive"><table class="table table-hover table-responsive-card"><thead><tr><th>No</th><th>Jenis</th><th>Judul</th><th>Dibagikan oleh</th><th>Kepada</th><th>Izin</th><th>Status</th><th>Tanggal</th><th>Aksi</th></tr></thead><tbody>@forelse($riwayat as $index => $item)<tr><td data-label="No">{{ $loop->iteration }}</td><td data-label="Jenis"><span class="badge {{ $item->type === 'soal' ? 'bg-primary' : 'bg-success' }}">{{ ucfirst($item->type) }}</span></td><td data-label="Judul">@if($item->type === 'soal'){{ Str::limit($item->question->question_text ?? '-',50) }}@else{{ $item->paketSoal->name ?? '-' }}@endif</td><td data-label="Dibagikan oleh">{{ $item->sharedBy->name ?? '-' }}</td><td data-label="Kepada">{{ $item->sharedTo->name ?? '-' }}</td><td data-label="Izin"><span class="badge bg-info">{{ $item->permission_label }}</span></td><td data-label="Status">@if($item->is_accepted)<span class="badge bg-success">Diterima</span>@elseif($item->deleted_at)<span class="badge bg-danger">Ditolak</span>@else<span class="badge bg-warning">Pending</span>@endif</td><td data-label="Tanggal"><small class="text-muted">{{ $item->created_at->format('d M Y') }}</small></td><td data-label="Aksi"><a href="{{ route('share.detail', ['type' => $item->type, 'id' => $item->id]) }}" class="btn btn-sm btn-outline-primary"><i class="fas fa-eye"></i></a></td></tr>@empty<tr><td colspan="9" class="text-center py-5"><i class="fas fa-history fa-2x text-muted mb-3 d-block"></i><p class="text-muted mb-0">Belum ada riwayat kolaborasi.</p></td></tr>@endforelse</tbody></table></div>@isset($riwayat)<div class="card-foot d-flex justify-content-end">{{ $riwayat->links() }}</div>@endisset</div>
</div>
@endsection