@extends('layouts.app')

@section('title', 'Edit Soal')
@section('breadcrumb', 'Edit Soal')
@section('breadcrumb_parent', 'Bank Soal')
@section('breadcrumb_parent_url', route('questions.index'))

@section('content')
@php
    $pgLabels = ['A','B','C','D','E'];
    $pgOptions = array_map(fn($label) => $question->pgOptions->firstWhere('label',$label)?->option_text ?? '', $pgLabels);
    if (count($pgOptions) < 4) $pgOptions = array_pad($pgOptions, 4, '');
    $correctOption = collect($pgLabels)->search(fn($label) => (bool)($question->pgOptions->firstWhere('label',$label)?->is_correct ?? false));
    $correctOption = $correctOption === false ? 0 : $correctOption;
@endphp
<div class="container-fluid">
<div class="stat-card" x-data="questionForm()" x-init="type='{{ $question->type }}'; level='{{ $question->level_c }}'; options=@js($pgOptions); correctOption={{ $correctOption }}; correctBoolean={{ $question->correct_boolean ? 'true' : 'false' }}; loadKKO(level)">
<h5 class="fw-bold mb-4">Edit Soal</h5>
<form action="{{ route('questions.update',$question) }}" method="POST">@csrf @method('PUT')<input type="hidden" name="type" x-model="type">
<div class="mb-4"><label class="form-label fw-bold">Tipe Soal</label><div class="row g-2">@foreach([['pg','fa-list-ul','PG'],['uraian','fa-pen','Uraian'],['menjodohkan','fa-link','Menjodohkan'],['benar_salah','fa-check-circle','Benar/Salah']] as $item)<div class="col-md-3"><div class="type-selector-card {{ $question->type === $item[0] ? 'active':'' }}" :class="{active:type==='{{ $item[0] }}'}" @click="type='{{ $item[0] }}'"><i class="fas {{ $item[1] }}"></i><span class="d-block fw-bold">{{ $item[2] }}</span></div></div>@endforeach</div></div>
<div class="row mb-3"><div class="col-md-4"><label class="form-label fw-bold">Mata Pelajaran</label><div class="input-group"><select name="subject_id" class="form-select" required>@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected(old('subject_id',$question->subject_id)==$subject->id)>{{ $subject->name }}</option>@endforeach</select><a href="{{ route('subjects.create') }}" class="btn btn-outline-primary"><i class="fas fa-plus"></i></a></div></div><div class="col-md-4"><label class="form-label fw-bold">Jenjang</label><select name="jenjang" class="form-select" required>@foreach(['SD','SMP','SMA'] as $j)<option value="{{ $j }}" @selected(old('jenjang',$question->jenjang)==$j)>{{ $j }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label fw-bold">Kurikulum</label><select name="curriculum" class="form-select" required><option value="merdeka" @selected(old('curriculum',$question->curriculum)=='merdeka')>Merdeka</option><option value="kbc" @selected(old('curriculum',$question->curriculum)=='kbc')>KBC</option><option value="both" @selected(old('curriculum',$question->curriculum)=='both')>Merdeka & KBC</option></select></div></div>
<div class="row mb-3"><div class="col-md-6"><label class="form-label fw-bold">Level Kognitif</label><select name="level_c" class="form-select" x-model="level" @change="loadKKO(level)" required><option value="L1">L1 - Pengetahuan & Pemahaman</option><option value="L2">L2 - Penerapan</option><option value="L3">L3 - Penalaran / HOTS</option></select></div><div class="col-md-6"><label class="form-label fw-bold">KKO</label><select name="kko_id" class="form-select" required><option value="">Pilih KKO</option><template x-for="kko in kkoOptions" :key="kko.id"><option :value="kko.id" x-text="`${kko.verb} (${kko.level})`" :selected="kko.id == {{ $question->kko_id }}"></option></template></select></div></div>
<div class="mb-3"><label class="form-label fw-bold">Teks Soal</label><textarea name="question_text" class="form-control" rows="5" required>{{ old('question_text',$question->question_text) }}</textarea></div>
<div class="mb-4"><label class="form-label fw-bold">Area Jawaban</label><div x-show="isPG"><template x-for="(option,index) in options" :key="index"><div class="input-group mb-2"><span class="input-group-text"><input type="radio" name="correct_option" :value="index" x-model="correctOption"></span><input type="text" :name="`options[${index}]`" class="form-control" x-model="options[index]"></div></template><button type="button" class="btn btn-sm btn-outline-secondary" @click="addOption()" x-show="options.length<5"><i class="fas fa-plus"></i> Tambah Opsi</button></div><div x-show="isUraian"><textarea name="rubric_text" class="form-control" rows="4">{{ old('rubric_text',$question->essayRubric->rubric_text ?? '') }}</textarea></div><div x-show="isMenjodohkan">@foreach($question->matchingPairs as $index=>$pair)<div class="row g-2 mb-2"><div class="col-md-6"><input type="text" name="left_texts[{{ $index }}]" class="form-control" value="{{ old('left_texts.'.$index,$pair->left_text) }}"></div><div class="col-md-6"><input type="text" name="right_texts[{{ $index }}]" class="form-control" value="{{ old('right_texts.'.$index,$pair->right_text) }}"></div></div>@endforeach</div><div x-show="isBenarSalah"><button type="button" class="btn btn-success me-2" @click="correctBoolean=true">Benar</button><button type="button" class="btn btn-danger" @click="correctBoolean=false">Salah</button><input type="hidden" name="correct_boolean" :value="correctBoolean"></div></div>
<div class="mb-4"><label class="form-label fw-bold">Indikator Soal</label><textarea name="indicator_text" class="form-control" rows="2">{{ old('indicator_text',$question->indicator_text) }}</textarea></div><button type="submit" class="btn btn-primary"><i class="fas fa-save me-1"></i> Update Soal</button> <a href="{{ route('questions.index') }}" class="btn btn-outline-secondary">Batal</a>
</form></div></div>
@endsection
